[program:app]
command=/srv/app/start_ckan.sh
priority=500
user=www-data
group=www-data
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
